### ISSUE TITLE
hsbeat cause io wait high !

### ISSUE THREAD

**Issue by kkpbbb** [YaSuenag/hsbeat#2] opened 2016-01-17 03:19 UTC
Hi，I try to use the hsbeat collect the JVM info. 
I found it cause the System TOP command CPU wa% from 1% to 70% even more!
My system is centos 6 and java version info is 
openjdk version "1.8.0_65"
OpenJDK Runtime Environment (build 1.8.0_65-b17)
OpenJDK 64-Bit Server VM (build 25.65-b01, mixed mode)

can we use the javaagent like hsflowd http://blog.sflow.com/2011/09/java-virtual-machine.html to monitor jvm performance ?

thanks 

sorry for my bad english

**Comment by YaSuenag** [comment] 2016-01-17 14:33
Thank you for reporting!

I've fixed performance issue of file access:
https://github.com/YaSuenag/hsbeat/commit/12152565ae39b9a2ba7f9dc9d6b86ae12a6b0269

However, we might encounter performance issue.
When I ran (new) hsbeat with profiler, it spent CPU time in libbeat publisher and JSON processing.

It might be improved with index structure in ES.
I will continue to work for it in [performance-improvement branch](https://github.com/YaSuenag/hsbeat/tree/performance-improvement) .

**Comment by YaSuenag** [comment] 2016-02-16 15:12
I improved performance of HSBeat than before:
https://github.com/YaSuenag/hsbeat/commit/4031b8b7377d8c4ab59c5874b1e888321e93cb64

[profile.zip](https://github.com/YaSuenag/hsbeat/files/132707/profile.zip)

I've attached CPU profile callgraph of it.
- Machine: Fedora23 x86_64 Hyper-V virtual machine (2 vcpu / 2GB mem)
- Host CPU: Intel Core i3 2367M 1.4GHz
- HSBeat collection interval: 10 sec

This profile shows that top overhead is GC routine.
To eliminate them, I implemented entry cache of hsperfdata entries.

It is too difficult to improve more performance.
But I will try it :-)

**Comment by kkpbbb** [comment] 2016-02-17 11:12
Thanks
I give it a try and found io wait is low ,but user and system cpu is very high and use so much more memory finally cause the jvm killed by oom!

**Comment by YaSuenag** [comment] 2016-02-17 13:44
I guess that high CPU usage is caused by Go runtime.

``` test.patch
diff --git a/hsbeat/hsbeat.go b/hsbeat/hsbeat.go
index 4dede96..c2a5632 100644
--- a/hsbeat/hsbeat.go
+++ b/hsbeat/hsbeat.go
@@ -135,18 +135,22 @@ func (this *HSBeat) publishCached(b *beat.Beat) error {
 }

 func (this *HSBeat) Run(b *beat.Beat) error {
+/*
   err := this.publishAll(b)
   if err != nil {
     return err
   }
+*/

   for !this.ShouldTerminate {
     time.Sleep(this.Interval)

+/*
     err := this.publishCached(b)
     if err != nil {
       return err
     }
+*/

   }

diff --git a/main.go b/main.go
index f2d0c83..3912898 100644
--- a/main.go
+++ b/main.go
@@ -28,7 +28,7 @@ import (

   hsbeat "github.com/YaSuenag/hsbeat/hsbeat"

-  //"runtime/pprof"
+  "runtime/pprof"
 )


@@ -38,14 +38,18 @@ func main() {
     log.Fatal(err)
   }

-/*
-  prof, err := os.Create("hsbeat.prof")
+  prof, err := os.Create("hsbeat.pprof")
   if err != nil {
     log.Fatal(err)
   }
   pprof.StartCPUProfile(prof)
   defer pprof.StopCPUProfile()
-*/
+
+  mprof, err := os.Create("hsbeat.mprof")
+  if err != nil {
+    log.Fatal(err)
+  }
+  defer pprof.WriteHeapProfile(mprof)

   hb :=&hsbeat.HSBeat{os.Args[1], time.Duration(interval), "",
                                                        false, nil, nil, nil}
```

I applied above patch (this patch makes empty loop in Beat), but I saw high CPU usage.
![top](https://cloud.githubusercontent.com/assets/7421132/13111134/8c90e500-d5c7-11e5-8d12-c7da79793686.png)

CPU profiling shows futex call is the most expensive in profiling session.
[profile.zip](https://github.com/YaSuenag/hsbeat/files/134404/profile.zip)

Conclusion:
We have to work for more performance improvement. However, we might not be able to avoid overhead in Go runtime.

**Comment by ruflin** [comment] 2016-02-17 14:55
@YaSuenag Which libbeat version are you currently using for hsbeat?

**Comment by YaSuenag** [comment] 2016-02-18 14:37
@ruflin I use v1.0.0 (be66518)

**Comment by ruflin** [comment] 2016-02-18 16:13
@YaSuenag I didn't check the issue in detail but in general it could help to upgrade the most recent version of libbeat.

**Comment by YaSuenag** [comment] 2016-02-20 14:48
I fixed this issue in https://github.com/YaSuenag/hsbeat/commit/e02c891f7df82cfaacab98a421d07a3c141884c2 !
I close this issue but kibana,json in current HEAD (above commit) does not support this changes.

So I will fix it soon in another commit.

**Comment by YaSuenag** [comment] 2016-02-20 14:48
CPU usage in https://github.com/YaSuenag/hsbeat/commit/e02c891f7df82cfaacab98a421d07a3c141884c2 is < 1% in my machine. Try it!

**Closed as completed by YaSuenag** 2016-02-20 14:48 UTC

**Comment by kkpbbb** [comment] 2016-02-22 05:36
Hi
Thanks for your fix.
I give it a try ,every things is fine.
But there no any data in elasticsearch except the common header!!
Is that correct ?? You have comment too many code ?
![image](https://cloud.githubusercontent.com/assets/12478971/13210318/1c02c2d6-d969-11e5-9da1-9ddfb7602d9e.png)

**Comment by YaSuenag** [comment] 2016-02-22 05:56
It is correct.
I've disabled _source in dynamic template to reduce cost of Elasticsearch:
  https://github.com/YaSuenag/hsbeat/commit/c0a9dffc7ea1d80874064bc069c04826dd04ab62

You can see data on Kibana dashboard if you import etc/kibana.json .
